project:
  type: default
  #output-dir: _output
  output-dir: ../docs

format:
  pdf:
    documentclass: article
    geometry:
      - margin=1in
    number-sections: true
    toc: true
    include-in-header:
      text: |
        \usepackage{lineno}
        \linenumbers
  html:
    theme: cosmo
    toc: true

execute:
  echo: false
  warning: false
  message: false
